use_frameworks!

target 'DVIA-v2' do
    pod 'Parse', '1.17.3'
    pod 'GoogleAnalytics'
    pod 'RealmSwift'
    pod 'couchbase-lite-ios'
    pod 'libwebp', '1.3.0'
    pod 'Flurry-iOS-SDK/FlurrySDK', '12.0.0'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
